---
title: "TOPUP PERFORMANCE"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(reshape2)
library(gridExtra)
library(scales)
source('ggplot_theme_Publication-2.R')

df <- read.csv('MB2_TOPUP_MOBILE.csv', sep = "|")
df <- df %>% mutate_at(vars(contains('DATE')), ~(as.Date(., '%m/%d/%Y')))
cam_date <- as.Date('14/9/2022', '%d/%m/%Y')
mod_date <- as.Date('1/10/2022', '%d/%m/%Y')
mod_date_ <- as.Date('1/11/2022', '%d/%m/%Y')
before <- df %>% filter(TRAN_DATE < cam_date)
after <- df %>% filter(TRAN_DATE >= cam_date)
model1_ls_10 <- read.csv('VIB20_CLIENT_FILE_FOR_TOPUP_28SEP.csv')
model2_ls_11 <- read.csv('VIB20_TOPUPv2_POTENTIAL_2022_11.csv')
model1_ls_11 <- read.csv('VIB20_CLIENT_FILE_FOR_TOPUP_22_11_02.csv')
performance <- data.frame(Model = NA,
                            Month = NA,
                          Export = NA,
                          Match = NA)
performance <- rbind(performance, data.frame(Model = 'Model 1', 
                                            Month = 'OCT 2022',
                                            Export = nrow(model1_ls_10),
                                            Match = nrow(inner_join(model1_ls_10, after %>% filter(TRAN_DATE >= mod_date), on = 'CLIENT_NO') %>% select(CLIENT_NO) %>% unique())))
performance <- rbind(performance, data.frame(Model = 'Model 1', 
                                            Month = 'NOV 2022',
                                            Export = nrow(model1_ls_11),
                                            Match = nrow(inner_join(model1_ls_11, after %>% filter(TRAN_DATE >= mod_date_), on = 'CLIENT_NO') %>% select(CLIENT_NO) %>% unique())))
                                            
performance <- rbind(performance, data.frame(Model = 'Model 2', 
                                            Month = 'NOV 2022',
                                            Export = nrow(model2_ls_11),
                                            Match = nrow(inner_join(model2_ls_11, after %>% filter(TRAN_DATE >= mod_date_), on = 'CLIENT_NO') %>% select(CLIENT_NO) %>% unique())))
performance <- na.omit(performance)
performance <- performance %>% mutate(Precision = Match / Export)
```

Model performance {.tabset}
===================
Row
-----------------------------------------------------------------------

### During campaign

```{r}
y_max <- max(performance %>% select(is.numeric))
scaleRight <- 100 / y_max
plot1 <- ggplot(melt(performance %>% filter(Model == 'Model 1') %>% select(-Precision, -Model) %>% mutate(Month = factor(Month, levels = c('OCT 2022', 'NOV 2022')))), aes(x = Month)) +
    geom_bar(aes(y = value, fill = variable, color = variable),  stat = 'identity', position = "dodge") +
    geom_point(data = performance %>% filter(Model == 'Model 1'), aes( y = Precision * 100 / scaleRight, group = 1, color = 'Precision'), size = 3) +
    geom_line(data = performance %>% filter(Model == 'Model 1'), aes( y = Precision * 100 / scaleRight, group = 1, color = 'Precision'), size = 1) +
    geom_text(data = performance %>% filter(Model == 'Model 1'), aes(y = (Precision * 100 + 5) / scaleRight , label = paste(round(Precision,2)*100, '%'), color = 'Precision'),show.legend=F) +
    # scale_color_manual(values = c('black')) +
    scale_y_continuous(labels = comma, expand = expansion(mult = c(0,.05)),
                    sec.axis = sec_axis(~.*scaleRight, name = "Precision (%)",
                                        breaks=seq(0,100,10))) +
    # theme_classic() +
    scale_fill_Publication() + 
    scale_colour_Publication()+
    theme_Publication() +
    guides(color = guide_legend(nrow = 1),fill="none") +
    labs( y="# Cust", x="Month") +
    theme(axis.text.x = element_text(angle=90, vjust=0.6),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),
        legend.background = element_rect(fill = "transparent"), 
      legend.box.background = element_rect(fill = "transparent", colour = NA),
      legend.key = element_rect(fill = "transparent"), 
      legend.spacing = unit(-1, "lines"),
      legend.title=element_blank(), plot.title = element_text(face="bold", size = 20))
plot1
# ggplotly(p, tooltip = c('y','x')) %>% config(displayModeBar = F)
```

### After campaign

Campaign performance {.tabset}
===================
Row
-----------------------------------------------------------------------

### Transaction frequency
```{r}
tmp <- df %>% mutate(TIME = format(TRAN_DATE, "%Y-%m")) %>%  
                group_by(TIME) %>% 
                summarise(ATF = n())
ggplot() + 
geom_line(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ATF, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ATF, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ATF, group = 1, color = 'During campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ATF, group = 1, color = 'During campaign'), size = 5) +
scale_y_continuous(labels = comma) +
labs(x = 'Month', y = 'Transaction frequency') +
theme_Publication() +
scale_color_manual(values = c('grey','#f87f01')) + 
theme(legend.title = element_blank())

```


### Average elapse between consecutive transactions


```{r}
tmp_func <- function(vec) {
    if (length(vec) > 1){
        return(as.numeric(mean(diff(vec))))
    } else {
        return(0)
    }
}
tmp <- df %>% mutate(TIME = format(TRAN_DATE, "%Y-%m")) %>% 
        group_by(TIME,CLIENT_NO, TRAN_DATE) %>% 
        arrange(TRAN_DATE) %>% 
        group_by(TIME, CLIENT_NO) %>% 
        summarise(Dif = tmp_func(TRAN_DATE)) %>%
        group_by(TIME) %>%
        summarise(ADif = mean(Dif))
ggplot() + 
geom_line(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ADif, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ADif, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ADif, group = 1, color = 'During campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ADif, group = 1, color = 'During campaign'), size = 5) +
# geom_line(aes(x = TIME, y = ADif, group = 1, color = 'Avg'), size = 1) +
# geom_point(aes(x = TIME, y = ADif, group = 1, color = 'Avg'), size = 5) +
# geom_segment(aes(x = '2022-09', xend = '2022-09',y=-Inf, yend = max(ADif), color = 'Campaign Date'), linetype = 'dashed') +
# geom_text(aes(x = '2022-09', y = max(ADif) - 0.05, label = 'Campaign Date', color = 'Campaign Date'), hjust = 1) +
labs(x = 'Month', y = 'Average elapse (days)') +
theme_Publication() +
scale_color_manual(values = c('grey','#f87f01')) + 
theme(legend.position = 'none')
```

### Average transaction frequency per customer

```{r}
tmp <- df %>% mutate(TIME = format(TRAN_DATE, "%Y-%m")) %>%  group_by(TIME , CLIENT_NO) %>% summarise(n = n()) %>% group_by(TIME) %>% summarise(ATF = mean(n))
# ggplot(tmp) + 
ggplot() + 
geom_line(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ATF, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ATF, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ATF, group = 1, color = 'During campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ATF, group = 1, color = 'During campaign'), size = 5) +

# geom_line(aes(x = TIME, y = ATF, group = 1, color = 'Avg'), size = 1) +
# geom_point(aes(x = TIME, y = ATF, group = 1, color = 'Avg'), size = 5) +
# geom_segment(aes(x = '2022-09', xend = '2022-09',y=-Inf, yend = max(ATF), color = 'Campaign Date'), linetype = 'dashed') +
# geom_text(aes(x = '2022-09', y = max(ATF) - 0.05, label = 'Campaign Date', color = 'Campaign Date'), hjust = 1) +
labs(x = 'Month', y = 'Average transaction frequency') +
# scale_fill_Publication() + 
theme_Publication() +
scale_color_manual(values = c('grey','#f87f01')) + 
theme(legend.position = 'none')
```

Row
-----------------------------------------------------------------------

### Wonback ratio

```{r}
tmp <- df %>% mutate(TIME = format(TRAN_DATE, "%Y-%m")) %>%
            group_by(TIME, CLIENT_NO) %>%
            summarise(Total = n(), Subtotal = n()-1) %>%
            mutate(WR = Subtotal / Total) %>% group_by(TIME) %>% summarise(WR = mean(WR))
# ggplot(tmp) + 
ggplot() + 
geom_line(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = WR, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = WR, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = WR, group = 1, color = 'During campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = WR, group = 1, color = 'During campaign'), size = 5) +
# geom_line(aes(x = TIME, y = WR, group = 1, color = 'Avg'), size = 1) +
# geom_point(aes(x = TIME, y = WR, group = 1, color = 'Avg'), size = 5) +
# geom_segment(aes(x = '2022-09', xend = '2022-09',y=-Inf, yend = max(WR), color = 'Campaign Date'), linetype = 'dashed') +
# geom_text(aes(x = '2022-09', y = max(WR), label = 'Campaign Date', color = 'Campaign Date'), hjust = 1) +
labs(x = 'Month', y = 'Wonback ratio') +
# scale_fill_Publication() + 
theme_Publication() +
scale_color_manual(values = c('grey','#f87f01')) + 
theme(legend.position = 'none')
```

### Topup amount

```{r}
tmp <- df %>% mutate(TIME = format(TRAN_DATE, "%Y-%m")) %>%  
                group_by(TIME) %>% 
                summarise(ATF = sum(TRAN_AMOUNT)/10^9)
# ggplot(tmp) + 
ggplot() + 
geom_line(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ATF, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ATF, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ATF, group = 1, color = 'During campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ATF, group = 1, color = 'During campaign'), size = 5) +
# geom_line(aes(x = TIME, y = ATF, group = 1, color = 'Avg'), size = 1) +
# geom_point(aes(x = TIME, y = ATF, group = 1, color = 'Avg'), size = 5) +
# geom_segment(aes(x = '2022-09', xend = '2022-09',y=-Inf, yend = max(ATF), color = 'Campaign Date'), linetype = 'dashed') +
# geom_text(aes(x = '2022-09', y = max(ATF) - 0.05, label = 'Campaign Date', color = 'Campaign Date'), hjust = 1) +
labs(x = 'Month', y = 'Topup amount (B)') +
# scale_fill_Publication() + 
theme_Publication() +
scale_color_manual(values = c('grey','#f87f01')) + 
theme(legend.position = 'none')
```

### Average Topup amount per cust

```{r}
tmp <- df %>% mutate(TIME = format(TRAN_DATE, "%Y-%m")) %>%  group_by(TIME , CLIENT_NO) %>% summarise(n = sum(TRAN_AMOUNT)/10^3) %>% group_by(TIME) %>% summarise(ATF = mean(n))
# ggplot(tmp) + 
ggplot() + 
geom_line(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ATF, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-07','2022-08','2022-09')), aes(x = TIME, y = ATF, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ATF, group = 1, color = 'During campaign'), size = 1) +
geom_point(data = tmp %>% filter(TIME %in% c('2022-09','2022-10','2022-11')), aes(x = TIME, y = ATF, group = 1, color = 'During campaign'), size = 5) +
# geom_line(aes(x = TIME, y = ATF, group = 1, color = 'Avg'), size = 1) +
# geom_point(aes(x = TIME, y = ATF, group = 1, color = 'Avg'), size = 5) +
# geom_segment(aes(x = '2022-09', xend = '2022-09',y=-Inf, yend = max(ATF), color = 'Campaign Date'), linetype = 'dashed') +
# geom_text(aes(x = '2022-09', y = max(ATF), label = 'Campaign Date', color = 'Campaign Date'), hjust = 1) +
labs(x = 'Month', y = 'Average Topup amount per cust (K)') +
# scale_fill_Publication() + 
theme_Publication() +
scale_color_manual(values = c('grey','#f87f01')) + 
theme(legend.position = 'none')
```

### Acquisition performance

```{r}
tmp <- df %>% filter(TRAN_DATE >= cam_date) %>% 
                mutate(TIME = format(TRAN_DATE, "%Y-%m")) %>% 
                group_by(TIME, CLIENT_NO) %>% 
                summarise(first = min(TRAN_DATE))
tmp <- left_join(tmp, df %>% select(CLIENT_NO, IB_REGISTERED_DATE2) %>% unique(), )
tmp <- tmp %>% ungroup() %>% mutate(Ratio = as.numeric(first - cam_date) / as.numeric(first - IB_REGISTERED_DATE2))
tmp %>% filter(!is.na(tmp),!is.infinite(Ratio)) %>% group_by(TIME) %>% summarise(Ratio = mean(Ratio, na.rm = TRUE)) %>%
ggplot() +
geom_line(aes(x = TIME, y = Ratio, group = 1, color = 'Avg'), size = 1) +
geom_point(aes(x = TIME, y = Ratio, group = 1, color = 'Avg'), size = 5) +
geom_segment(aes(x = '2022-09', xend = '2022-11',y=1, yend = 1, color = 'Line'), linetype = 'dashed') +
geom_text(aes(x = '2022-10', y = 1, label = 'Acquisition line', color = 'Line'), hjust = -1, vjust = 2) +
labs(x = 'Month', y = 'Acquisition performance') +
scale_fill_Publication() + 
theme_Publication() +
  scale_color_manual(values = c('#f87f01','black')) + 
theme(legend.position = 'none')
```
